### ISSUE TITLE
Getting Error "Permission denied, please try again."

### ISSUE THREAD

**Issue by attacker007** [hackingguy/Bug-Hunting-Colab#10]
Hi Team,

I wanted to connect to ssh but i am getting this Error when system ask for password...

```
Warning: Permanently added the ECDSA host key for IP address '[3.6.115.182]:17240' to the list of known hosts.
Permission denied, please try again.

```

I've deleted the known hosts file but still not able to login.. Even Rotated the ngrok Token... but still not working !!

**Comment by singhjeevan30** [comment]
> Hi Team,
> 
> I wanted to connect to ssh but i am getting this Error when system ask for password...
> 
> ```
> Warning: Permanently added the ECDSA host key for IP address '[3.6.115.182]:17240' to the list of known hosts.
> Permission denied, please try again.
> ```
> 
> I've deleted the known hosts file but still not able to login.. Even Rotated the ngrok Token... but still not working !!

i am getting the same error... akash bro asked to reset runtime... but still getting the same error... Akash bhai.. help!

**Comment by singhjeevan30** [comment]
And another error i am facing is noVNC encountered an error... what's the reason for this? any solutions!?

**Comment by hackingguy** [comment]
I think its your individual issue! Please Check this out! Go to Runtime->Factory Reset Runtime
You can see its working perfectly fine!
May be internet connection issue!

![Annotation 2020-09-02 194343](https://user-images.githubusercontent.com/28388650/91994802-a76a0380-ed54-11ea-9cc7-5dafab74b05d.png)

**Comment by attacker007** [comment]
Hi @hackingguy  Thanks.. Issue Resolved..I deleted the known host files...Restarted Laptop and its working now !
But I am getting "No GPU Available"
