### ISSUE TITLE
NoVNC Encountered an error

### ISSUE THREAD

**Issue by singhjeevan30** [hackingguy/Bug-Hunting-Colab#11]
noVNC encountered an error:

Uncaught SyntaxError: The requested module './util/int.js' does not provide an export named 'toSigned32bit'
http://123456.in.ngrok.io/vnc.html?autoconnect=true&password=Ns9sVhD02aveB5STemVc:0:0
SyntaxError: The requested module './util/int.js' does not provide an export named 'toSigned32bit'

I am getting the above error... any suggestions to mitigate it?
plz help.

**Comment by hackingguy** [comment]
I think its your individual issue! Please Check this out! Go to Runtime->Factory Reset Runtime
You can see its working perfectly fine!
May be internet connection issue!

![Annotation 2020-09-02 194343](https://user-images.githubusercontent.com/28388650/91994802-a76a0380-ed54-11ea-9cc7-5dafab74b05d.png)

**Comment by singhjeevan30** [comment]
thanks bro... i figured a way to make this work... just one small help
again..
i mounted my google drive but how to import the contents of my last
session... can u please elaborate?
Regards,

**Comment by hackingguy** [comment]
cd /content/drive/
