### ISSUE TITLE
is it safe enough？

### ISSUE THREAD

**Issue by y360u** [hackingguy/Bug-Hunting-Colab#12]

**Comment by hackingguy** [comment]
Its not a issue, you need to ask this thing on twitter or medium!
BTW Answers!
Is it Safe?
Yes!
Is it Completely Legal?
No!
Can It Ban My Gmail Account?
Yes if you are doing **bitcoin mining** like stuff, no if used as normal vps!

**Comment by attacker007** [comment]
Hi @hackingguy  is it good for privacy.. Like for researcher's data is being saved on your device or somewhere else?

**Comment by hackingguy** [comment]
You shouldn't ask these kind of things on github, please contact me on twitter [twitter.com/hackingguyak](Here), if you want to discuss anything, maintain development decorum here. Its not a chatting place
