### ISSUE TITLE
ssh_exchange_identification: Connection closed by remote host

### ISSUE THREAD

**Issue by dkdhaval** [hackingguy/Bug-Hunting-Colab#14]
when i try to connect in cmd shoing this error 
ssh_exchange_identification: Connection closed by remote host

**Comment by aksl337** [comment]
#13 pull request is for same issue. it will be updated sooner, meanwhile try to run "apt-get update && apt-get upgrade" before "apt-get install openssh-server" it will work fine.

**Comment by dkdhaval** [comment]
i am using windows machine to connect and i tried both cmd and mobaxterm  but both are showing above error

**Comment by hackingguy** [comment]
Solved By @aksl337 in #13 Pull Request!
Check Now!
I have Updated Version to 1.4.0!
So Old Versions Will Automatically get OTA Update!

**Comment by d4rkh0rse** [comment]
again this issue happend

ssh_exchange_identification: Connection closed by remote host
