### ISSUE TITLE
Runtime disconnected

### ISSUE THREAD

**Issue by dkdhaval** [hackingguy/Bug-Hunting-Colab#15]
Hello i tried on my 2 gmail accounts and diffrent ngrok  account but in both account its shows runtime disconnected errors
i clear ram and everting but not solved

![Untitled](https://user-images.githubusercontent.com/8256271/95671223-dbd1aa80-0bb1-11eb-8101-54ca454b572d.png)

**Comment by hackingguy** [comment]
Hi! Thanks Alot For Reporting! 
I fixed the bug just needed to change the version!
You can click again on open in colab!
Its Working Perfectly Fine Now

**Comment by dkdhaval** [comment]
thank you
