### ISSUE TITLE
again this issue happend ssh_exchange_identification: Connection closed by remote host

### ISSUE THREAD

**Issue by d4rkh0rse** [hackingguy/Bug-Hunting-Colab#16]
again this issue happend

ssh_exchange_identification: Connection closed by remote host

_Originally posted by @d4rkh0rse in https://github.com/hackingguy/Bug-Hunting-Colab/issues/14#issuecomment-716992617_

**Comment by singhjeevan30** [comment]
i am facing the same issue too. don't know why is this happening.

**Comment by attacker007** [comment]
Getting same issue..

**Comment by hackingguy** [comment]
Hi Guys, Sorry for the late reply as I was busy with my exams, Actually I checked the issue and found that Google Colab has started blocking ngrok requests. So, we have to change tunneling or manually set up the connection with ngrok every time. 
**Soon I am gonna change tunneling to Cloudflare or get some bypass for this.**
Until that, I recommend using [Colab-SSH](https://github.com/WassimBenzarti/colab-ssh)  and make a ngrok connection.
And then starting VNC Server

**Comment by singhjeevan30** [comment]
thanks alot Akash!!

**Comment by hackingguy** [comment]
Sorry for the delay! Removed Ngrok and added Argotunnel! Now working fluently!
