### ISSUE TITLE
Tunnel not found on No VNC

### ISSUE THREAD

**Issue by bugtestingbb** [hackingguy/Bug-Hunting-Colab#20]
Hi @hackingguy ,

While trying to access the VPS with noVnc I'm getting this error `Tunnel 90e208c0ab90.in.ngrok.io not found`
and also try to access via ssh also getting error `kex_exchange_identification: Connection closed by remote host`

Any solution for the above?

**Comment by MrViNC3R3** [comment]
Same issue , tried factory reset runtime also , still the issue persist

**Comment by hackingguy** [comment]
Hi Guys, Sorry for the late reply as I was busy with my exams, Actually I checked the issue and found that Google Colab has started blocking ngrok requests. So, we have to change tunneling or manually set up the connection with ngrok every time. 
**Soon I am gonna change tunneling to Cloudflare or get some bypass for this.**
Until that, I recommend using [Colab-SSH](https://github.com/WassimBenzarti/colab-ssh)  and make a ngrok connection.
And then starting VNC Server

**Comment by bugtestingbb** [comment]
Hi, do u have documentation/video to setup it?

**Comment by hackingguy** [comment]
Sorry for the delay! Removed Ngrok and added Argotunnel! Now working fluently!

**Comment by attacker007** [comment]
Hi @hackingguy  Thanks a lot.. Will you make short video tutorial for the updated one.. As u made for the Ngrok ..
