### ISSUE TITLE
Installation Guide For Naive Users

### ISSUE THREAD

**Issue by vlakhani28** [hackingguy/Bug-Hunting-Colab#23]
Hey

I did not want to open this issue but installing the VPS is being a bit confusing as all the videos are of the old method (without Argo Tunnel)

I tried installing cloudflared from the website given in the documentation but as soon as i login it asks me to authorize argo tunnel and gets stuck over here
![image](https://user-images.githubusercontent.com/42069316/103534417-d3d58e00-4eb4-11eb-820d-75f239da4d88.png)

My power shell shows something like this
![image](https://user-images.githubusercontent.com/42069316/103534481-f10a5c80-4eb4-11eb-89e3-f1db30a5d81b.png)

It would be very helpful if you could guide me as i am not able to understand using the documentation

Also if you could create a video on how exactly to do it using the new version would be of great help as all other videos are using the old version

Thanks

**Comment by gaaaary** [comment]
I hope to explain the new operating method

**Comment by vlakhani28** [comment]
Could to you please explain then

**Comment by kannanG-pro** [comment]
we are waiting for your **installation** guide ...

**Comment by Iron-Hide** [comment]
Yes, If possible please try to create a video of how exactly we can make use of this new version as the mentioned steps are slightly confusing.

**Comment by hackingguy** [comment]
Get Installation Link From [Here](https://developers.cloudflare.com/argo-tunnel/getting-started/installation)
Add The Binary/Exe In PATH env variables (Learn From [Here](https://www.architectryan.com/2018/08/31/how-to-change-environment-variables-on-windows-10/))

**Comment by vlakhani28** [comment]
Hey 
I downloaded the binary and added it to the Environment Variable

![image](https://user-images.githubusercontent.com/42069316/106098148-8fa97680-615e-11eb-8443-acc5207cfc9c.png)

I ran the command on the collab then and tried to connect the ssh but it says failed

![image](https://user-images.githubusercontent.com/42069316/106098188-a354dd00-615e-11eb-8b77-6031a0e998b4.png)

Could you pls let us know the next steps (A video might be useful)

**Comment by hackingguy** [comment]
Hi, You just need to add folder to environment variables not exe file.
Just remove cloudflare.exe and keep ending directory '/' 
Use this:
```
C:\Users\Vaibhav\Downloads\Compressed\
```

**Comment by vlakhani28** [comment]
Hey,
Done the changes the ssh still seems to time out.
![image](https://user-images.githubusercontent.com/42069316/106119420-3439b180-617b-11eb-96d8-2e249f45ce93.png)

![image](https://user-images.githubusercontent.com/42069316/106119397-2d12a380-617b-11eb-85b4-cbeb5aa15341.png)

**Comment by hackingguy** [comment]
I am adding a detailed readme within 10-20 mins! I hope it will help you!

**Comment by vlakhani28** [comment]
That would be very helpful! Thank you for your help and constant support😄

**Comment by hackingguy** [comment]
https://youtu.be/bJUr0SnBpEM Here is Video Tutorial!

**Comment by vlakhani28** [comment]
Hey,
I followed the video as it is the ssh is still refusing to connect!

I tried using the Chrome Remote Desktop Method but it seems to have an error in the code after i enter the Debian Command

![image](https://user-images.githubusercontent.com/42069316/106152648-b4740d00-61a3-11eb-8402-4a1f0de4add1.png)

**Comment by hackingguy** [comment]
There is no issue in chrome remote desktop! yes it shows error but it works even after it! I will remove error someday! Just check remote access you will see some device online

**Comment by vlakhani28** [comment]
Perfect yes its running fine! Thank you for all the help sir! :D
