### ISSUE TITLE
i have problem

### ISSUE THREAD

**Issue by shadihh9** [hackingguy/Bug-Hunting-Colab#5]
when i finish open vps I open again not connect 
![looooooooooooooooooo](https://user-images.githubusercontent.com/22076930/89801485-e8497080-db38-11ea-83e2-078d4c3bfda8.png)

**Comment by shadihh9** [comment]
and disconnect  when i open

**Comment by hackingguy** [comment]
Do not Close The Tab! 
If you close the tab it will disconnect!

**Comment by hackingguy** [comment]
And Try VNC Connection In Background Atleast will not disconnect for 2-4 hrs!
If Disconnects, Click On Reconnect Button. Problem will be resolved!

**Comment by shadihh9** [comment]
Tunnel bda2a9be77b4.in.ngrok.io not found

**Comment by shadihh9** [comment]
![vnc](https://user-images.githubusercontent.com/22076930/89830839-8bb07a80-db65-11ea-8c94-92cce5bd4882.png)

**Comment by hackingguy** [comment]
> ![vnc](https://user-images.githubusercontent.com/22076930/89830839-8bb07a80-db65-11ea-8c94-92cce5bd4882.png)
> 

I think you should restart google collab, there must be a option to reboot Colab Runtime!

**Comment by shadihh9** [comment]
i do and not solve Tunnel 3f0a44828e38.in.ngrok.io not found

**Comment by shadihh9** [comment]
![bhhhh](https://user-images.githubusercontent.com/22076930/89861100-a4dd1980-dbad-11ea-9bca-37819178ec7f.png)

**Comment by hackingguy** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/28388650/89868423-67d64e80-dbd0-11ea-9517-56f2eb3c0794.png)
There Is Some Issue At Your End I Just Checked , There Is No Problem And One More Thing, Don't Close The Colab Tab else you get disconnect!

**Comment by shadihh9** [comment]
solve this problem and thanks

**Comment by shadihh9** [comment]
please help and fix this problem and tell me who to fix not normally open all time tab because I turn off laptop

**Comment by shadihh9** [comment]
any fix yet

**Comment by shadihh9** [comment]
fix problem Connection to tcp.in.ngrok.io closed by remote host.
Connection to tcp.in.ngrok.io closed. support vnc copy data and past like copy url

**Comment by shadihh9** [comment]
when iwork or run tool the vps is display this error  Connection to tcp.in.ngrok.io closed by remote host.
Connection to tcp.in.ngrok.io closed

**Comment by hackingguy** [comment]
Please Try Our New Update! A contributor made a pull request!
