### ISSUE TITLE
Please update it to first release version

### ISSUE THREAD

**Issue by penetrationexpert** [hackingguy/Bug-Hunting-Colab#8]
hello,
it's an updated version of script throwing error of ngrok and remote host please release it to first version 1.2.0 it was working fine and running without errors.the new updated version is throwing lots of errors.
like this
```

Failed to complete tunnel connection

The connection to http://0e3d56a12d8d.in.ngrok.io was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address localhost:6080.

Make sure that a web service is running on localhost:6080 and that it is a valid address.

The error encountered was: dial tcp 127.0.0.1:6080: connect: connection refused

```

**Comment by aksl337** [comment]
Try latest version I fixed firefox issue and regarding your ngrok issue maybe issue with your tokens.try it on latest version without changing anything just adding your ngrok tokens.as i just(after your comment) checked latest version and its working fine.

**Comment by hackingguy** [comment]
If You Want A Old Release, Just Use Old One And Change The Version or remove the UpdateCheck
