### ISSUE TITLE
Error Issue

### ISSUE THREAD

**Issue by Acretia** [hackingguy/Bug-Hunting-Colab#9]
Hi, 

I get problem on step "7. Now Wait for 10 Minutes As It is gonna install all important tools from every epic infosec community member!"

The process takes so long and display some error:

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/usr/lib/python3.6/urllib/request.py in do_open(self, http_class, req, **http_conn_args)
   1324                 h.request(req.get_method(), req.selector, req.data, headers,
-> 1325                           encode_chunked=req.has_header('Transfer-encoding'))
   1326             except OSError as err: # timeout error

17 frames
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

URLError                                  Traceback (most recent call last)
URLError: <urlopen error [Errno 99] Cannot assign requested address>

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
/root/.ipython/ttmg.py in nameport(self, TOKEN, AUTO)
     43             tokens['your'] = __temp[0].split(':')[1]
     44             clear_output()
---> 45     return tokens['your']
     46 
     47 

KeyError: 'your'

It happen on Chrome and Firefox.

Thank you.

**Comment by hackingguy** [comment]
Sorry For The Issue! I Resolved it! Please Try And Run Again! It will definitely work!

**Comment by Acretia** [comment]
Thank you. Will check it asap
